### ISSUE TITLE
Class not found: block_exacomp\globals

### ISSUE THREAD

**Issue by SephGER** [gtn/exacomp#10]
In unserem Moodle kommt beim Klick auf Importieren im Block die Fehlermeldung

`Class not found: 'block_exacomp\globals'`

Nach einigem Debuggen und schnüffeln im Code habe ich herausgefunden, dass der Ort an dem dies Auftritt die Datei `'classes\api.php'` ist

Wenn ich hier unter der Datei `inc.php` zusätzlich noch `lib/common.php` einbinde funktioniert es. 
Wo könnte da der Fehler liegen? Bei Anderen scheint es ja auch ohne diese Änderung zu klappen und ich würde nur ungerne dauerhaft im Code Dinge ändern die beim nächsten Update wieder weg sind...

**Comment by dangerer** [comment]
die Datei common.php wird über die Datei lib.php eingebunden, ihre Änderung sollte grundsätzlich nicht notwendig sein.
Können sie mir ihre Moodle, exacomp und Serverversion mitteilen?
