### ISSUE TITLE
block_exacomp\task\autotest should not loop through all courses

### ISSUE THREAD

**Issue by rschrenk** [gtn/exacomp#16]
The task "autotest" ist configured to run each time cron is carried out. Unfortunately, it is rather inefficient, as it loops all courses that use block_exacomp to spot if some quizzes have been finished. It would be better to implement an event listener.

**Comment by richardwolfmayr** [comment]
Thank you for the advice. This has now been implemented. The event "course_module_completion_updated" is used to trigger an observer and update the grading of related exacomp competencies instead of looping over every quiz/activity in the cron.
