### ISSUE TITLE
many activities produce internal server error

### ISSUE THREAD

**Issue by lassnj** [gtn/exacomp#20]
If there are a lot of activities in a course, trying to Realte Moodle Activities in the Competence Grid block results in an internal server error. There is a request timeout after 1 minute and 51 seconds. Please make the block work with better performance, so that the site can be loaded. If there are not many activities in the course, the problem does not occur.

**Comment by richardwolfmayr** [comment]
When exactly does the timeout occur? When loading and displaying the page, or only when saving the relations?

**Comment by lassnj** [comment]
When loading and displaying the page, so I cannot even open the page.
