### ISSUE TITLE
Wrong use of $CFG->tempdir

### ISSUE THREAD

**Issue by rschrenk** [gtn/exacomp#8]
Sites can configure an alternative location for the temp dir by setting $CFG->tempdir.

Unfortunately your plugin breaks this setting by using a hardcoded style to set the tempdir based on the dataroot ($CFG->dataroot . '/temp/backup').

Please change the according lines so that they respect an alternative $CFG->tempdir.

- blocks/exacomp/activities_to_descriptors.php line163
- blocks/exacomp/classes/data.php line 1234

**Comment by dasistwas** [comment]
Fix analog zu:
stefanscholz/moodle-format_kickstart@cfe60a0
