### ISSUE TITLE
Fehler beim Öffnen der Webservice API Dokumentation

### ISSUE THREAD

**Issue by rschrenk** [gtn/exacomp#9]
Beim Öffnen der Moodle Webservice API Dokumentation (/admin/webservice/documentation.php) kommt folgender Fehler, der auf block_exacomp hindeutet.

> Ausgabepuffer:  <div class="notifytiny debuggingmessage" data-rel="debugging">External function parameters: invalid OPTIONAL value specified.<ul style="text-align: left" data-rel="backtrace"><li>line 729 of /lib/externallib.php: call to debugging()</li><li>line 12478 of /blocks/exacomp/externallib.php: call to external_function_parameters->__construct()</li><li>line 122 of /lib/externallib.php: call to block_exacomp_external::dakora_competencegrid_overview_parameters()</li><li>line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">External function parameters: invalid OPTIONAL value specified.<ul style="text-align: left" data-rel="backtrace"><li>line 729 of /lib/externallib.php: call to debugging()</li><li>line 7366 of /blocks/exacomp/externallib.php: call to external_function_parameters->__construct()</li><li>line 122 of /lib/externallib.php: call to block_exacomp_external::diggrplus_get_competence_profile_statistic_parameters()</li><li>line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">External function parameters: invalid OPTIONAL value specified.<ul style="text-align: left" data-rel="backtrace"><li>line 729 of /lib/externallib.php: call to debugging()</li><li>line 6715 of /blocks/exacomp/externallib.php: call to external_function_parameters->__construct()</li><li>line 122 of /lib/externallib.php: call to block_exacomp_external::diggrplus_get_examples_and_items_parameters()</li><li>line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">External function parameters: invalid OPTIONAL value specified.<ul style="text-align: left" data-rel="backtrace"><li>line 729 of /lib/externallib.php: call to debugging()</li><li>line 6933 of /blocks/exacomp/externallib.php: call to external_function_parameters->__construct()</li><li>line 122 of /lib/externallib.php: call to block_exacomp_external::diggrplus_get_teacher_examples_and_items_parameters()</li><li>line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">External function parameters: invalid OPTIONAL value specified.<ul style="text-align: left" data-rel="backtrace"><li>line 729 of /lib/externallib.php: call to debugging()</li><li>line 6352 of /blocks/exacomp/externallib.php: call to external_function_parameters->__construct()</li><li>line 122 of /lib/externallib.php: call to block_exacomp_external::diggrplus_submit_item_parameters()</li><li>line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">External function parameters: invalid OPTIONAL value specified.<ul style="text-align: left" data-rel="backtrace"><li>line 729 of /lib/externallib.php: call to debugging()</li><li>line 41 of /filter/oembed/classes/webservice/ws_providers.php: call to external_function_parameters->__construct()</li><li>line 122 of /lib/externallib.php: call to filter_oembed\webservice\ws_providers::service_parameters()</li><li>line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()</li></ul></div>

**Comment by dangerer** [comment]
this was fixed
